services:
  database:
    image:
      postgres
    container_name: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "15231523"
    volumes:
      - ./db.sql:/var/database/db.sql

  pgadmin:
    image:
      dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "1523"
    volumes:
      - ./servers.json:/pgadmin4/servers.json 
    depends_on:
      - database
    
    
